trigger: none

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  # The pipeline extends the 1ES PT which will inject different SDL and compliance tasks.
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: 'TSA-Windows-Hosted-Pool'

    stages:
    - stage: Stage
      jobs:
      - job: HostJob
        steps:
        - powershell: |
            mkdir "$(Build.ArtifactStagingDirectory)/ArtifactOutputs"
        templateContext:
          outputs:
          - output: pipelineArtifact
            path: $(Build.ArtifactStagingDirectory)/ArtifactOutputs
            artifact: drop
