name: CI

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 20
        cache: npm

    - name: npm ci
      run: npm ci

    - name: npm run build
      run: npm run build -- --env CONNECTION_STRING="${{ secrets.CONNECTION_STRING }}"

    # - name: npm run test
    #   run: npm run test

    - name: Install tfx-cli
      run: npm install -g tfx-cli

    - name: Package extension
      run: >
        tfx extension create
        --manifests vss-extension.json vss-extension.prod.json
        --output-path sariftools.scans.vsix

    - name: Package dev extension
      run: >
        tfx extension create
        --manifests vss-extension.json vss-extension.dev.json
        --output-path sariftools.scans-dev.vsix

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: vsix
        path: '*.vsix'
